# Generated by Django 4.2.7 on 2023-12-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photorate', '0004_delete_userrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Фото'),
        ),
    ]
