# Generated by Django 4.2.7 on 2023-12-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photorate', '0007_alter_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=None, verbose_name='Оценка'),
        ),
    ]
