# Generated by Django 4.2.7 on 2023-12-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photorate', '0008_alter_photos_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True, verbose_name='Оценка'),
        ),
    ]
