# Generated by Django 4.2.7 on 2024-01-04 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photorate', '0009_alter_photos_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='rate',
        ),
        migrations.AddField(
            model_name='photos',
            name='post_dislike',
            field=models.ManyToManyField(blank=True, related_name='post_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photos',
            name='post_like',
            field=models.ManyToManyField(blank=True, related_name='post_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7)),
                ('for_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forPost', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
