# Generated by Django 4.2.7 on 2024-01-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photorate', '0011_rating_delete_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='post_dislike',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='post_like',
        ),
    ]
